name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      artifact:
        type: choice
        description: 'artifact type'
        required: true
        default: 'Api'
        options:
          - 'Api'
          - 'Batch'
      versionup:
        type: choice
        description: 'version up type'
        required: true
        default: 'patch'
        options:
          - 'major'
          - 'minor'
          - 'patch'

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}
          fetch-depth: 0

      - name: Get latest tag
        id: get-latest-tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 --match "${{ github.event.inputs.artifact }}-v*")
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_OUTPUT

      - name: Version Up
        id: version-up
        run: |
          latest_tag=${{ steps.get-latest-tag.outputs.LATEST_TAG }}
          version=$(echo $latest_tag | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')

          if [ ${{ github.event.inputs.versionup }} == "major" ]; then
            new_version=$(echo $version | awk -F'.' '{printf "%d.%d.%d", $1 + 1, 0, 0}')
          elif [ ${{ github.event.inputs.versionup }} == "minor" ]; then
            new_version=$(echo $version | awk -F'.' '{printf "%d.%d.%d", $1, $2 + 1, 0}')
          else
            new_version=$(echo $version | awk -F'.' '{printf "%d.%d.%d", $1, $2, $3 + 1}')
          fi

          echo "NEW_VERSION=$new_version" >> $GITHUB_OUTPUT

      - name: Create and push release branch
        run: |
          new_version=${{ steps.version-up.outputs.NEW_VERSION }}
          git checkout -b release/${{ github.event.inputs.artifact}}-v$new_version
          git push origin release/${{ github.event.inputs.artifact}}-v$new_version