name: Create Hotfix Branch

on:
  workflow_dispatch:
    inputs:
      artifact:
        type: choice
        description: 'artifact type'
        required: true
        default: 'Api'
        options:
          - 'Api'
          - 'Batch'

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}
          fetch-depth: 0

      - name: Get latest tag
        id: get-latest-tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 --match "${{ github.event.inputs.artifact }}-v*")
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_OUTPUT

      - name: Create and push hotfix branch
        run: |
          git checkout -b hotfix/${{ github.event.inputs.artifact}}-v${{ steps.get-latest-tag.outputs.LATEST_TAG }}+1
          git push origin hotfix/${{ github.event.inputs.artifact}}-v${{ steps.get-latest-tag.outputs.LATEST_TAG }}+1
