name: Create Hotfix Branch

on:
  workflow_dispatch:
    inputs:
      artifact:
        type: choice
        description: 'artifact type'
        required: true
        default: 'Api'
        options:
          - 'Api'
          - 'Batch'

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}
          fetch-depth: 0

      - name: Get latest tag
        id: get-latest-tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 --match "${{ github.event.inputs.artifact }}-v*")
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_OUTPUT

      - name: Create and push hotfix branch
        run: |
          tag=${{ steps.get-latest-tag.outputs.LATEST_TAG }}
          version_regex="([0-9]+\.[0-9]+\.[0-9]+)\+(\d+)"
          if [[ $tag =~ $version_regex ]]; then
              base_version="${BASH_REMATCH[1]}"
              build_number="${BASH_REMATCH[2]}"
          else
              base_version="$tag"
              build_number=""
          fi

          # 빌드 번호를 증가시키거나 +1을 붙여 새로운 버전 문자열 생성
          if [ -z "$build_number" ]; then
              new_version="$base_version+1"
          else
              new_build_number=$((build_number+1))
              new_version="$base_version+$new_build_number"
          fi

          echo "$new_version"

          git checkout -b hotfix/$new_version
          git push origin hotfix/$new_version
