name: Deploy - Production Environment

on: 
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy-production-environment:
    runs-on: 'ubuntu-latest'
    if: github.event.pull_request.merged == true
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Get Tag
        id: get-tag
        run: |
          echo "현재 브랜치 확인 - ${{ github.head_ref }}"
          branch=${{ steps.branch-names.outputs.current_branch }}
          new_tag="${branch#release/}"
          new_tag=$(echo "${new_tag}" | sed 's/-/ /g')

          echo $new_tag
          echo "NEW_TAG=$new_tag" >> $GITHUB_OUTPUT

      - name: Check Tag
        run: |
          echo ${{ steps.get-tag.outputs.NEW_TAG }}

      - name: Create Release & Tag 
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-tag.outputs.NEW_TAG }}
          release_name: ${{ steps.get-tag.outputs.NEW_TAG }}
          body: |
            ${{ github.event.pull_request.body }}

      - name: 'Deploy Production Environment'
        run: |
          echo "Deploy Production Environment"