name: Deploy - Production Environment

on:
  push:
    tags:
      - Api-v*

jobs:
  deploy-production-environment:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Deploy Script
        run: |
          echo "Deploy Production Environment"