name: Deploy - Development Environment

on: 
  create:
  push:
    branches:
      - release/Api-v*
      - hotfix/Api-v*

jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      current_branch: ${{ steps.branch-name.outputs.current_branch }}
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

  deploy-development-environment:
    needs: check-branch
    runs-on: 'ubuntu-latest'
    if: startsWith(${{ needs.check-branch.outputs.current_branch}}, 'release/Api-v') || startsWith(${{ needs.check-branch.outputs.current_branch}}, 'hotfix/Api-v')
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Deploy Development Environment'
        run: |
          echo "Deploy Development Environment"