name: Auto-merge Dependabot
on:
  push:
    branches:
      - main

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}
          fetch-depth: 0

      - name: Get latest tag
        id: get-latest-tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 --match "${{ github.event.inputs.artifact }}-v*")
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.MY_TOKEN }}
          commit-message: 'new version deploy ${{ steps.get-latest-tag.outputs.LATEST_TAG }}'
          title: 'Release Version - ${{ steps.get-latest-tag.outputs.LATEST_TAG }}'
          body: '새 버전 출시 완료 ${{ steps.get-latest-tag.outputs.LATEST_TAG }}'
          branch: 'main'
          base: 'develop'
          delete-branch: false